### ISSUE TITLE
Help to troubleshoot generators in my app

### ISSUE THREAD

**Issue by asianfilm** [keathley/norm#46] opened 2020-02-07 01:58 UTC
While the rest of the library is working well for me, I haven't been able to get generators working.

For example, here's a REPL session:

```elixir
iex> Application.ensure_all_started(:stream_data)
{:ok, []}

iex> int_spec = spec(is_integer())
#Norm.Spec<is_integer()>

iex> int_spec |> gen() |> Enum.take(1)
** (Protocol.UndefinedError) protocol Norm.Generatable not implemented for #Norm.Spec<is_integer()> of type Norm.Spec (a struct) 

iex> int_generator = with_gen(int_spec), StreamData.integer(0..3))
%Norm.Generator{conformer: #Norm.Spec<is_integer()>, generator: :null}

iex> int_generator |> gen() |> Enum.take(1)
** (Norm.GeneratorLibraryError) In order to use generators please include `stream_data` as a dependency
```

It's not my installation of Elixir (1.9.4) because when I clone this repository, I can run its tests and execute the above successfully when inside its project folder.

Is there some configuration I need to add to `application.ex` when using `StreamData` as a library? Or do the error messages above point to a likely issue in my setup?

Here's my `mix.exs` file (edited):
```elixir
  defp deps do
    [
      {:norm, "~> 0.10.3"},
      {:stream_data, "~> 0.4.3", optional: true, only: [:dev, :test]},
      ...
    ]
  end
```

Thanks in advance.

**Comment by keathley** [comment] 2020-02-07 12:49
The error message "In order to use generators please include `stream_data` as a dependency" seems to indicate that you might need to force a recompilation with `mix deps.compile norm --force`. I've seen this happen before when norm is compiled before stream_data has been added to the project.

**Comment by asianfilm** [comment] 2020-02-08 01:39
Thanks. That fixed it. Not sure why wiping my `_build` directory didn't have the same effect.

**Comment by QuinnWilton** [comment] 2020-05-02 01:22
I've noticed this problem popping up intermittently when setting up projects that depend on `Norm`, even if `StreamData` is also in the project. Is there a way to force `Norm` to be compiled after `StreamData`? Right now, as a workaround, I'm also running `mix deps.compile norm --force` in my Dockerfile, to avoid running into the issue during production builds.

**Comment by keathley** [comment] 2020-05-02 15:01
@QuinnWilton I'm honestly not sure :/. I've also seen this happen before. I'm not familiar enough with the compiler to know what the right solution is. We might have to make the checks for stream data a runtime check instead of a compile time check. I'm not sure if there is a clean way to do that yet. I suspect that if we solve this we can also solve #63 at the same time.

**Comment by Qqwy** [comment] 2020-06-13 10:28
I encountered this issue today as well, where a co-worker downloaded the project and ran `mix deps.get; iex -S mix` for the first time. I believe the problem is that Mix does not consider optional dependencies in its compilation order. It compiles packages that are not inter-dependent in alphabetical order, resulting in `norm` being compiled before `stream_data` is available.

**Comment by keathley** [comment] 2020-06-13 15:42
Closing this for now. If the problem reappears feel free to comment or reopen.

**Closed** 2020-06-13 15:41 UTC

**Comment by francishamel** [comment] 2020-08-05 22:00
I still have this problem. If I delete the `_build` folder and try to use a Norm generator, I get the same error. Currently using version `0.12.0` of Norm and `0.5.0` of StreamData.

**Comment by chouzar** [comment] 2020-08-29 23:57
Hi @keathley, maybe as a reminder it would it be a good idea to put a small note on the [Generators section](https://hexdocs.pm/norm/Norm.html#module-generators) of the docs. 

Would also be nice if the error could be extended in the lines of:

```
** (Norm.GeneratorLibraryError) In order to use generators please include `stream_data` as a dependency; you might need to force norm's recompilation with mix deps.compile norm --force
    (norm 0.12.0) lib/norm.ex:104: Norm.gen/1
```

If you like the idea I could try and do the PR.

**Comment by keathley** [comment] 2020-08-30 13:21
I have a fix for this in the works.
